cmake_minimum_required(VERSION 4.1)
project()

set(CMAKE_CXX_STANDARD 20)

add_executable(main.cpp
        Algorithm1-10/arithmetic1.cpp
        Algorithm1-10/arithmetic2.cpp
        Algorithm1-10/arithmetic3.cpp
        Algorithm1-10/arithmetic4构造链表.cpp
        cmake-build-debug/arithmetic.cpp
        Algorithm1-10/arithmetic5.cpp
        Algorithm1-10/arithmetic6.cpp
        Algorithm1-10/arithmetic7.cpp
        Algorithm1-10/arithmetic8.cpp
        Algorithm1-10/arithmetic9.cpp
        Algorithm1-10/arithmetic10.cpp
        Algorithm11-20/球票大赛11.cpp
        Algorithm11-20/年龄问题12.cpp
        Algorithm11-20/猜年龄13.cpp
        Algorithm11-20/门牌制作14.cpp
        Algorithm11-20/国庆星期几15.cpp
        Algorithm11-20/受伤的皇后16.cpp
        Algorithm11-20/青蛙跳17.cpp
        Algorithm11-20/日期问题18.cpp
        Algorithm11-20/插入排序18.cpp
        Algorithm11-20/二分法19.cpp
        Algorithm21-30/21大数加法.cpp
        Algorithm21-30/22gcd算法.cpp
        Algorithm21-30/23素数算法.cpp
        Algorithm21-30/24快速幂.cpp
        Algorithm11-20/20既约分数.cpp
        Algorithm21-30/25组素数.cpp
        Algorithm21-30/26分数.cpp
        Algorithm21-30/27最大公约数.cpp
        Algorithm21-30/28归并排序.cpp
        Algorithm21-30/29递归问题.cpp
        Algorithm21-30/30堆结构.cpp
        Algorithm31-40/31桶排序.cpp
        Algorithm31-40/32快速排序.cpp
        "Algorithm31-40/33(1)哈希表.cpp"
        Algorithm31-40/34有序表map_set.cpp
        Algorithm31-40/35静态链表_动态链表.cpp
        Algorithm31-40/36环状链表.cpp
        Algorithm31-40/37双向环状链表.cpp
        Algorithm31-40/38链表是否为回文结构.cpp
        Algorithm31-40/39给链表划分区域.cpp
        "Algorithm31-40/40(1)复制含有随机指针节点的链表.cpp"
        "Algorithm31-40/40(2)链表分区为三段.cpp"
        "Algorithm31-40/40(3)判断两条单链表是否成环是否相交.cpp"
        Algorithm41-50/42怎么求二叉树的最大宽度.cpp
        Algorithm41-50/43二叉树给先序中序求后序.cpp
        Algorithm41-50/41二叉树.cpp
        Algorithm41-50/44搜索二叉树.cpp
        "Algorithm41-50/50DFS(1).cpp"
        Algorithm41-50/45完全二叉树.cpp
        "Algorithm41-50/46满二叉树 平衡二叉树.cpp"
        Algorithm41-50/47运算符.cpp
        Algorithm41-50/48两个节点的最低公共祖先.cpp
        Algorithm41-50/49二叉树凹凸中序遍历.cpp
        Algorithm51-60/51图.cpp
        Algorithm51-60/52图的BFS_DFS算法.cpp
        Algorithm51-60/53图的拓扑排序.cpp
        Algorithm51-60/54图的kruskal算法.cpp
        Algorithm51-60/55图的prime算法.cpp
        Algorithm51-60/56图的Dijkstra算法.cpp
        Algorithm51-60/57前缀树Trie.cpp
        Algorithm51-60/58贪心算法.cpp
        Algorithm51-60/59对数器.cpp
        "Algorithm31-40/33(2)哈希函数哈希表的实现.cpp"
        Algorithm51-60/60最短网络图的prim算法.cpp
        Algorithm61-70/61完全二叉树权值.cpp
        Algorithm61-70/62大臣的旅费.cpp
        "Algorithm61-70/63贪心算法(问问题).cpp"
        "Algorithm61-70/64dp(1)动态规划.cpp"
        "Algorithm41-50/50DFS(2)跳台阶.cpp"
        "Algorithm41-50/50DFS(3)指数型实现.cpp"
        "Algorithm41-50/50DFS(4)组合的输出.cpp"
        "Algorithm41-50/50DFS(5)5道习题.cpp"
        "Algorithm61-70/64dp(2).cpp"
        "Algorithm61-70/64dp(3).cpp"
        Algorithm61-70/62chongxie.cpp
        "Algorithm61-70/64dp(4).cpp"
        "Algorithm61-70/64dp(5).cpp"
        "Algorithm61-70/64dp(6)蜗牛.cpp"
        "Algorithm61-70/65滑动窗口(1).cpp"
        "Algorithm61-70/65滑动窗口(2)统计子矩阵.cpp"
        Algorithm61-70/66双指针.cpp
        Algorithm61-70/67前缀和.cpp
        Algorithm61-70/68最小栈.cpp
        Algorithm61-70/69随机选择算法.cpp
        "Algorithm61-70/70(1)归并排序.cpp"
        "Algorithm61-70/70(2)归并分治.cpp"
        Algorithm71-80/71二进制和位运算.cpp
        Algorithm71-80/72位运算的操作.cpp
        Algorithm71-80/73一维差分和等差数列差分.cpp
        Algorithm71-80/74二分搜索.cpp
        Algorithm71-80/75二维前缀二维差分离散化技巧.cpp
        Algorithm71-80/76二分答案法.cpp
        "Algorithm71-80/77(1)并查集.cpp"
        "Algorithm71-80/77(2)并差集打标签.cpp"
        Algorithm71-80/78洪水填充.cpp
        "Algorithm71-80/79建图 链式前向星 拓扑排序.cpp"
        Algorithm71-80/80拓扑排序拓展.cpp
        Algorithm81-90/81最小生成树MST.cpp
        Algorithm81-90/82BFS及其拓展.cpp
        Algorithm71-80/80重写.cpp
        Algorithm81-90/83双向广搜.cpp
        "Algorithm81-90/84Dijkstra算法 分层图最短路.cpp"
        Algorithm81-90/85A*,Bellman-Ford,SPFA.cpp
        Algorithm81-90/86一维dp.cpp
)
